### ISSUE TITLE
Floflis Mobile

### ISSUE THREAD

**Issue by danimesq** [Floflis/labs#3]
- [ ] Floflis Android ROM (https://github.com/Floflis/meta/issues/87)
- [ ] https://wiki.postmarketos.org/wiki/Porting_to_a_new_device
- [ ] Android apps using Anbox
- [ ] Floflis Screens Cellphone mode uses this (https://github.com/Floflis/meta/issues/78)
- [ ] Floflis for Raspberry Pi (https://github.com/Floflis/meta/issues/82)
